### ISSUE TITLE
Check what happens if a proposed upgrade maliciously breaks `initialize()`

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/subjectivocracy#76]
In `ForkingManager` we create both sides of the fork and call `initialize` against it. Assuming this code can be used for an upgrade and a new underlying library proposed, it's possible that the fork could be malicious and go out-of-gas or revert during `initialize`. We need to make sure that if this happens:

 * You can still deploy the other fork.
 * Anything else like bridges is also robust against a maliciously broken fork on one side or the other

**Comment by josojo** [comment]
The current behavior is that the whole transaction called `initiateFork` reverts. I think this is the best behavior, as this throws away the bad fork, and does not initiate the (no-changes) fork.

**Comment by edmundedgar** [comment]
Makes sense. Will leave this open as we have to make sure we can handle the case where initiateFork reverts in the preceding reality.eth game or whatever

**Comment by edmundedgar** [comment]
Thinking about how the l1 reality.eth arbitration contract would handle this: I guess detecting "maliciously broken upgrade proposition" by catching a revert or whatever is fiddly so we have to make 2 paths for an upgrade proposition:

- Normal path: Send an arbitration request with the fee and that automatically calls the ForkingManager and creates the fork in a single transaction.

- Maliciously broken upgrade path: Send the fee to the arbitration contract. Anybody can then run the query to forward the fee the ForkingManager and create the fork. If this does not complete within 1 week, the arbitration result is considered to be that the upgrade is rejected, and the arbitrator sends that to the reality.eth contract without doing a fork.

**Comment by josojo** [comment]
We solved it in the following way:
- the forking process always creates at least one legit fork that runs a successful initiated(since one fork is initiated with the current data).
- If the second fork does not initialize, its their faults and its okay (someone wasted quite some reality coins)

We have decided for this, since we can not know in advance whether an initialisation will revert or not.  If we would just revert the forking process, in case the initialization does not succeed, then we would create a state for the users in which they would not know which forkId they should use shortly in the future. We really wanna avoid this and hence decided for introducing the fork in any case.

@edmundedgar I think with that we can close it, right?

**Comment by edmundedgar** [comment]
I think on our current upgrade plan this is all moot, right? ie we can go back to creating the two forks simultaneously because they are always both just forks of the current ledger? Then if you want to do an upgrade you run that as an uncontested upgrade after the fork?
